db:
  image: thatpanda/postgis
  environment:
    USER: postgres
    PASS: root
    DB: location_service

api:
  build: .
  links:
    - db
  ports:
    - 8080
  volumes:
    - 'log:/var/log'
    - 'db/dbconf.yml:db/dbconf.yml'
